export const products = [
    {
        id: '1',
        name: 'Franela VH Negra',
        slug: 'franela-vh-negra',
        description: '<p>Disponible en variante manga larga, manga corta, sin mangas y con capucha.</p> <p><b>Tallas:</b> S, M, L, XL, XXL. <br /> <small>Preguntar disponibilidad si requiere otra talla en especifico.</small></p>',
        category: 'shirts',
        price: 'USD 20.00 ~ USD 28.00',
        images: [
            { id: '1', filename: 'black-01.png', },
            { id: '2', filename: 'black-02.png', },
            { id: '3', filename: 'black-03.png', },
        ],
        in_stock: false
    },
    {
        id: '2',
        name: 'Franela VH Verde',
        slug: 'franela-vh-verde',
        description: '<p>Disponible en variante manga larga, manga corta, sin mangas y con capucha.</p> <p><b>Tallas:</b> S, M, L, XL, XXL. <br /> <small>Preguntar disponibilidad si requiere otra talla en especifico.</small></p>',
        category: 'shirts',
        price: 'USD 20.00 ~ USD 28.00',
        images: [
            { id: '1', filename: 'green-01.png', },
            { id: '2', filename: 'green-02.png', },
            { id: '3', filename: 'green-03.png', },
        ],
        in_stock: false
    },
    {
        id: '3',
        name: 'Franela Caliza',
        slug: 'franela-Caliza',
        description: '<p>Disponible en variante manga larga, manga corta, sin mangas y franelilla. Con capucha tiene un costo adicional de USD $2.00.</p><p><b>Materiales disponibles:</b> Dryfit - Microperforada</p> <p><b>Tallas:</b> S, M, L, XL, XXL. <br /> <small>Preguntar disponibilidad si requiere otra talla en especifico.</small></p>',
        category: 'shirts',
        price: 'USD 20.00 ~ USD 28.00',
        images: [
            { id: '1', filename: 'caliza-01.png', genre: 'men' },
            { id: '2', filename: 'caliza-02.png', genre: 'men' },
            { id: '3', filename: 'caliza-03.png', genre: 'men' },
            { id: '4', filename: 'caliza-04.png', genre: 'men' },
            { id: '5', filename: 'caliza-05.png', genre: 'men' },
            { id: '6', filename: 'caliza-06.png', genre: 'men' },
            { id: '7', filename: 'caliza-07.png', genre: 'women' },
            { id: '8', filename: 'caliza-08.png', genre: 'women' },
            { id: '9', filename: 'caliza-09.png', genre: 'women' },
            { id: '10', filename: 'caliza-10.png', genre: 'women' },
            { id: '11', filename: 'caliza-11.png', genre: 'women' },
            { id: '12', filename: 'caliza-12.png', genre: 'women' },
            { id: '13', filename: 'caliza-13.png', genre: 'women' },
        ],
        in_stock: true
    },
    {
        id: '4',
        name: 'Franela Maco Maco',
        slug: 'franela-maco-maco',
        description: '<p>Disponible en variante manga larga, manga corta, sin mangas y franelilla. Con capucha tiene un costo adicional de USD $2.00.</p><p><b>Materiales disponibles:</b> Dryfit - Microperforada</p> <p><b>Tallas:</b> S, M, L, XL, XXL. <br /> <small>Preguntar disponibilidad si requiere otra talla en especifico.</small></p>',
        category: 'shirts',
        price: 'USD 20.00 ~ USD 28.00',
        images: [
            { id: '1', filename: 'macomaco-02-01.png', genre: 'men' },
            { id: '2', filename: 'macomaco-02-02.png', genre: 'men' },
            { id: '3', filename: 'macomaco-02-03.png', genre: 'men' },
            { id: '4', filename: 'macomaco-02-04.png', genre: 'men' },
            { id: '5', filename: 'macomaco-02-05.png', genre: 'men' },
            { id: '6', filename: 'macomaco-02-06.png', genre: 'men' },
            { id: '7', filename: 'macomaco-02-07.png', genre: 'men' },
            { id: '8', filename: 'macomaco-02-08.png', genre: 'men' },
            { id: '9', filename: 'macomaco-02-09.png', genre: 'women' },
            { id: '10', filename: 'macomaco-02-10.png', genre: 'women' },
            { id: '11', filename: 'macomaco-02-11.png', genre: 'women' },
            { id: '12', filename: 'macomaco-02-12.png', genre: 'women' },
            { id: '13', filename: 'macomaco-02-13.png', genre: 'women' },
            { id: '14', filename: 'macomaco-02-14.png', genre: 'women' },
            { id: '15', filename: 'macomaco-02-15.png', genre: 'women' },
        ],
        in_stock: true
    },
    {
        id: '5',
        name: 'Franela Sierra',
        slug: 'franela-sierra',
        description: '<p>Disponible en variante manga larga, manga corta, sin mangas y franelilla. Con capucha tiene un costo adicional de USD $2.00.</p><p><b>Materiales disponibles:</b> Dryfit - Microperforada</p> <p><b>Tallas:</b> S, M, L, XL, XXL. <br /> <small>Preguntar disponibilidad si requiere otra talla en especifico.</small></p>',
        category: 'shirts',
        price: 'USD 20.00 ~ USD 28.00',
        images: [
            { id: '1', filename: 'sierra-01.png', genre: 'men' },
            { id: '2', filename: 'sierra-02.png', genre: 'men' },
            { id: '3', filename: 'sierra-03.png', genre: 'men' },
            { id: '4', filename: 'sierra-04.png', genre: 'men' },
            { id: '5', filename: 'sierra-05.png', genre: 'men' },
            { id: '6', filename: 'sierra-06.png', genre: 'men' },
            { id: '7', filename: 'sierra-07.png', genre: 'women' },
            { id: '8', filename: 'sierra-08.png', genre: 'women' },
            { id: '9', filename: 'sierra-09.png', genre: 'women' },
            { id: '10', filename: 'sierra-10.png', genre: 'women' },
            { id: '11', filename: 'sierra-11.png', genre: 'women' },
            { id: '12', filename: 'sierra-12.png', genre: 'women' },
            { id: '13', filename: 'sierra-13.png', genre: 'women' },
        ],
        in_stock: true
    },
    {
        id: '6',
        name: 'Franela Nebula',
        slug: 'franela-nebula',
        description: '<p>Disponible en variante manga larga, manga corta, sin mangas y franelilla. Con capucha tiene un costo adicional de USD $2.00.</p><p><b>Materiales disponibles:</b> Dryfit - Microperforada</p> <p><b>Tallas:</b> S, M, L, XL, XXL. <br /> <small>Preguntar disponibilidad si requiere otra talla en especifico.</small></p>',
        category: 'shirts',
        price: 'USD 20.00 ~ USD 28.00',
        images: [
            { id: '1', filename: 'nebula-01.png', genre: 'men' },
            { id: '2', filename: 'nebula-02.png', genre: 'men' },
            { id: '3', filename: 'nebula-03.png', genre: 'men' },
            { id: '4', filename: 'nebula-04.png', genre: 'men' },
            { id: '5', filename: 'nebula-05.png', genre: 'women' },
            { id: '6', filename: 'nebula-06.png', genre: 'women' },
            { id: '7', filename: 'nebula-07.png', genre: 'women' },
            { id: '8', filename: 'nebula-08.png', genre: 'women' },
            { id: '9', filename: 'nebula-09.png', genre: 'women' },
            { id: '10', filename: 'nebula-10.png', genre: 'women' },
            { id: '11', filename: 'nebula-11.png', genre: 'women' },
        ],
        in_stock: true
    },
    {
        id: '7',
        name: 'Franela Sabana',
        slug: 'franela-sabana',
        description: '<p>Disponible en variante manga larga, manga corta, sin mangas y franelilla. Con capucha tiene un costo adicional de USD $2.00.</p><p><b>Materiales disponibles:</b> Dryfit - Microperforada</p> <p><b>Tallas:</b> S, M, L, XL, XXL. <br /> <small>Preguntar disponibilidad si requiere otra talla en especifico.</small></p>',
        category: 'shirts',
        price: 'USD 20.00 ~ USD 28.00',
        images: [
            { id: '1', filename: 'sabana-01.png', genre: 'men' },
            { id: '2', filename: 'sabana-02.png', genre: 'men' },
            { id: '3', filename: 'sabana-03.png', genre: 'men' },
            { id: '4', filename: 'sabana-04.png', genre: 'men' },
            { id: '5', filename: 'sabana-05.png', genre: 'men' },
            { id: '6', filename: 'sabana-06.png', genre: 'men' },
            { id: '7', filename: 'sabana-07.png', genre: 'women' },
            { id: '8', filename: 'sabana-08.png', genre: 'women' },
            { id: '9', filename: 'sabana-09.png', genre: 'women' },
            { id: '10', filename: 'sabana-10.png', genre: 'women' },
            { id: '11', filename: 'sabana-11.png', genre: 'women' },
            { id: '12', filename: 'sabana-12.png', genre: 'women' },
        ],
        in_stock: true
    },
        {
        id: '8',
        name: 'Buff Clásico Negro',
        slug: 'buff-clasico-negro',
        description: '<p><b>Tamaño:</b> 40&times;25 CM</p><p><b>Material:</b> Microdurazno</p>',
        category: 'accesories',
        price: 'USD 8.00',
        images: [
            { id: '1', filename: 'buff-black-01.png' },
        ],
        in_stock: true
    },
    {
        id: '9',
        name: 'Buff Nebula',
        slug: 'buff-nebula',
        description: '<p><b>Tamaño:</b> 40&times;25 CM</p><p><b>Material:</b> Microdurazno</p>',
        category: 'accesories',
        price: 'USD 8.00',
        images: [
            { id: '1', filename: 'buff-nebula-01.png' },
        ],
        in_stock: true
    },
    {
        id: '10',
        name: 'Buff Sabana',
        slug: 'buff-sabana',
        description: '<p><b>Tamaño:</b> 40&times;25 CM</p><p><b>Material:</b> Microdurazno</p>',
        category: 'accesories',
        price: 'USD 8.00',
        images: [
            { id: '1', filename: 'buff-sabana-01.png' },
        ],
        in_stock: true
    },
    {
        id: '11',
        name: 'Buff Sierra',
        slug: 'buff-sierra',
        description: '<p><b>Tamaño:</b> 40&times;25 CM</p><p><b>Material:</b> Microdurazno</p>',
        category: 'accesories',
        price: 'USD 8.00',
        images: [
            { id: '1', filename: 'buff-sierra-01.png' },
        ],
        in_stock: true
    },
    {
        id: '12',
        name: 'Toalla Mirador Casupo',
        slug: 'toalla-mirador-casupo',
        description: '<p>Fotografía por Tirso Lecointere</p><p><b>Tamaños disponibles</b> <ul><li>Pequeña: 35&times;71 CM</li><li>Grande: 67&times;137 CM</li></ul></p><p><b>Material:</b> Microfibra</p>',
        category: 'accesories',
        price: 'USD 12.00 ~ USD 25.00',
        images: [
            { id: '1', filename: 'toalla-mirador-01.png' },
            { id: '2', filename: 'toalla-mirador-02.png' },
        ],
        in_stock: true
    },
    {
        id: '13',
        name: 'Toalla Cerro El Café',
        slug: 'toalla-el-cafe',
        description: '<p>Fotografía por Gerardo Valero</p><p><b>Tamaños disponibles</b> <ul><li>Pequeña: 35&times;71 CM</li><li>Grande: 67&times;137 CM</li></ul></p><p><b>Material:</b> Microfibra</p>',
        category: 'accesories',
        price: 'USD 12.00 ~ USD 25.00',
        images: [
            { id: '1', filename: 'toalla-el-cafe-01.png' },
            { id: '2', filename: 'toalla-el-cafe-02.png' },
        ],
        in_stock: true
    },
]